// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalkAPI.Data;

#nullable disable

namespace NZWalkAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    partial class NZWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalkAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("364e2e8e-8027-4beb-9775-405545997ef0"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("a7110a23-5740-48a1-b018-89e8d47fc5f5"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("12881f7c-b772-46a3-a84e-142dc16104c7"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalkAPI.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            Code = "NTH",
                            Name = "Northland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Northland_region_map.png/800px-Northland_region_map.png"
                        },
                        new
                        {
                            Id = new Guid("d1f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Auckland_region_map.png/800px-Auckland_region_map.png"
                        },
                        new
                        {
                            Id = new Guid("e2f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            Code = "WAI",
                            Name = "Waikato",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Waikato_region_map.png/800px-Waikato_region_map.png"
                        });
                });

            modelBuilder.Entity("NZWalkAPI.Models.Domain.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            Description = "A scenic walk to the northernmost point of New Zealand.",
                            DifficultyId = new Guid("364e2e8e-8027-4beb-9775-405545997ef0"),
                            LengthInKm = 10.5,
                            Name = "Cape Reinga Walk",
                            RegionId = new Guid("c0f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            WalkImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Cape_Reinga_Walk.png/800px-Cape_Reinga_Walk.png"
                        },
                        new
                        {
                            Id = new Guid("aa0d1b17-5f27-4bde-81d1-905e0e7f23b0"),
                            Description = "A walk around the iconic Sky Tower in Auckland.",
                            DifficultyId = new Guid("12881f7c-b772-46a3-a84e-142dc16104c7"),
                            LengthInKm = 5.0,
                            Name = "Sky Tower Walk",
                            RegionId = new Guid("d1f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            WalkImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Sky_Tower_Walk.png/800px-Sky_Tower_Walk.png"
                        },
                        new
                        {
                            Id = new Guid("bbf9e091-1e43-48ab-b83f-5094e8b222c3"),
                            Description = "A walk to the stunning Huka Falls in Taupo.",
                            DifficultyId = new Guid("a7110a23-5740-48a1-b018-89e8d47fc5f5"),
                            LengthInKm = 8.0,
                            Name = "Huka Falls Walk",
                            RegionId = new Guid("e2f3a2b1-4d8e-4b5f-9c7d-5a2e6f3b8c1e"),
                            WalkImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Huka_Falls_Walk.png/800px-Huka_Falls_Walk.png"
                        });
                });

            modelBuilder.Entity("NZWalkAPI.Models.Domain.Walks", b =>
                {
                    b.HasOne("NZWalkAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalkAPI.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
